version: "3.9"

services:
  web:
    restart: unless-stopped
    build:
      context: .
    image: gmkhanaportal2024
    container_name: gmkhanaportal2024
    volumes:
        - "./static:/app/static"
        - "./media:/app/media"
        - "./gymkhana/migrations:/app/gymkhana/migrations"
    ports:
      - "127.0.0.1:9012:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env